[package]
name = "tictactoe"
description = "Template for starting a reView project using Trunk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
review = { path = "../../review" }
