name: Publish TicTacToe

permissions:
  contents: write

on: workflow_dispatch
jobs:
  publish:
    name: Publish TicTacToe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - run: |
          cd examples/tictactoe
          trunk build --release --public-url=review/tictactoe

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./examples/tictactoe/dist
          destination_dir: ./tictactoe
