name: Publish TicTacToe

permissions:
  contents: write

on: workflow_dispatch
jobs:
  publish:
    name: Publish TicTacToe
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
          profile: minimal

      - uses: jetli/trunk-action@v0.1.0
        with:
          version: "latest"

      - run: |
          cd examples/tictactoe
          trunk build --release --public-url=review/tictactoe

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./examples/tictactoe/dist
          target-folder: ./tictactoe
